# Generated by Django 3.0.3 on 2020-02-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20200205_1140'),
        ('accounts', '0002_auto_20200205_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
