# Generated by Django 3.0.3 on 2020-02-05 15:51

import datetime
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('ingridients', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=10)),
                ('drying_method', models.CharField(blank=True, max_length=100)),
                ('drying_time', models.IntegerField(blank=True, null=True)),
                ('photo_main', models.ImageField(upload_to=products.models.upload_image_path)),
                ('photo_1', models.ImageField(blank=True, upload_to=products.models.upload_image_path)),
                ('photo_2', models.ImageField(blank=True, upload_to=products.models.upload_image_path)),
                ('photo_3', models.ImageField(blank=True, upload_to=products.models.upload_image_path)),
                ('photo_4', models.ImageField(blank=True, upload_to=products.models.upload_image_path)),
                ('photo_5', models.ImageField(blank=True, upload_to=products.models.upload_image_path)),
                ('best_seller', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
