# Generated by Django 3.0.3 on 2020-02-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='item_sold',
            field=models.IntegerField(default=0),
        ),
    ]
