# Generated by Django 3.0.3 on 2020-02-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200204_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drying_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
